remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: HNB - RaBear
description: I am Game Developer
show_downloads: false
github:
  is_project_page: false
  zip_url: 
  tar_url: 
  repository_name: 